"""add cases, documents, golden_records, validation_results, pipeline_results

Revision ID: 12522c432f16
Revises: 
Create Date: 2026-08-10 11:51:33.283278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy
import db.models.types

# revision identifiers, used by Alembic.
revision: str = '12522c432f16'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')
    op.create_table('cases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('applicant_ref', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('RECEIVED', 'RUNNING', 'PASS', 'FAIL', 'NEEDS_REVIEW', name='case_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cases_applicant_ref'), 'cases', ['applicant_ref'], unique=True)
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('doc_type', sa.Enum('AADHAAR', 'PAN', 'ADDRESS_PROOF', 'SALARY_SLIP', 'BANK_STATEMENT', name='doc_type'), nullable=False),
    sa.Column('extracted_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_file_ref', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_case_id'), 'documents', ['case_id'], unique=False)
    op.create_table('golden_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('address_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('aadhaar_number', db.models.types.EncryptedString(), nullable=True),
    sa.Column('pan_number', db.models.types.EncryptedString(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id')
    )
    op.create_table('pipeline_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('decision', sa.Enum('PASS', 'FAIL', 'NEEDS_REVIEW', name='decision'), nullable=False),
    sa.Column('reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reviewer', sa.String(), nullable=True),
    sa.Column('review_status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='review_status'), nullable=True),
    sa.Column('reviewer_remarks', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_results_case_id'), 'pipeline_results', ['case_id'], unique=False)
    op.create_table('validation_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('check_type', sa.Enum('NAME', 'ADDRESS', 'AADHAAR', 'PAN', 'DOB', 'EMPLOYER', 'SALARY_DATE', 'SALARY_CREDIT_COUNT', 'MANDATORY_PRESENCE', name='check_type'), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validation_results_case_id'), 'validation_results', ['case_id'], unique=False)
    op.create_index(op.f('ix_validation_results_document_id'), 'validation_results', ['document_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_validation_results_document_id'), table_name='validation_results')
    op.drop_index(op.f('ix_validation_results_case_id'), table_name='validation_results')
    op.drop_table('validation_results')
    op.drop_index(op.f('ix_pipeline_results_case_id'), table_name='pipeline_results')
    op.drop_table('pipeline_results')
    op.drop_table('golden_records')
    op.drop_index(op.f('ix_documents_case_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_cases_applicant_ref'), table_name='cases')
    op.drop_table('cases')
    # ### end Alembic commands ###
